### PR TITLE
Compare FALCONN with brute force

### PR DESCRIPTION
**Pull request by gozdal**
I'm not affiliated in any way with FALCONN authors but thought it'd be fun to compare state of the art libraries for nearest-neighbor search with brute force.

### CODE REVIEW

**Comment by majek** [comment]
> On data sets with about 1 million points in around 100 dimensions, FALCONN typically requires a few milliseconds per query (running on a reasonably modern desktop CPU).

We do 1million points at 144 dimensions in 0.6ms.

**Comment by majek** [comment]
This is very impressive. At first I thought that the code cheats by using SMP, but I don't think it does. My only concern is that given the proposed parameters hyperplane gives wrong results
```
$ make falconn-hyperplane
Reading database 19106.091ms
Building index 3649.163ms
Total: 280.614ms, 1536 items, avg 0.183ms per query, 5473.706 qps
1363c1363
< sq_dist=65439 idx=156526
---
> sq_dist=929845 idx=623975
```

Which is a big warning sign, but I guess you explained it well that it's a matter for choosing the parameters. Thanks for the code!

**Comment by majek** [comment]
Also, memory usage seem _much_ worse, but I'm not sure how much that is a problem of FALCONN vs python3.

**Comment by gozdal** [comment]
I chose 200 more-or-less randomly. Original Python benchmarks use `2464`
https://github.com/FALCONN-LIB/FALCONN/blob/a4c0288edb2575b0306c5f6b4ab1f559b1e272a4/src/python/benchmark/random_benchmark.py#L143

I think SMP may be used when creating the LSH structure.

I am not sure about memory usage - only tested it with Python wrapper but the lib is C++.

**Pull request merged**
